package exit_codes

const (
	UNKNOWN_DRIVE                = 0x01
	CANNOT_READ_INITIAL_TRAIN    = 0x02
	ERROR_PLAYING_TRAIN_PLAYBOOK = 0x03
	MISSING_COMMAND_ARGUMENTS    = 0x04
	CUTOFF_TO_BIG                = 0x05
	ERROR_TRAINING_START         = 0x06
	NO_MATCHING_READS            = 0x07
	MEDIUM_NOT_PRESENT           = 0x08
	READ_AT_ONCE_TO_BIG          = 0x09
)
