package scsi

const (
	SECTOR_DATA_SIZE        = 2352
	SECTOR_C2_SIZE          = 294
	SECTOR_SUB_SIZE         = 16
	SECTOR_PAD_SIZE         = 2
	SECTOR_SYNC_SIZE        = 12
	SECTOR_DATA_C2_SIZE     = SECTOR_DATA_SIZE + SECTOR_C2_SIZE
	SECTOR_DATA_SUB_SIZE    = SECTOR_DATA_SIZE + SECTOR_SUB_SIZE
	SECTOR_DATA_C2_SUB_SIZE = SECTOR_DATA_SIZE + SECTOR_SUB_SIZE + SECTOR_C2_SIZE
	SECTOR_DATA_SUB_C2_SIZE = SECTOR_DATA_SIZE + SECTOR_C2_SIZE + SECTOR_SUB_SIZE
)

const (
	DATA        = 0
	DATA_C2     = 1
	DATA_SUB    = 2
	DATA_C2_SUB = 3
	DATA_SUB_C2 = 4
)
