package scsi

// Command Opcodes
const (
	MMC_READ_CD      = 0xBE
	MMC_SET_CD_SPEED = 0xBB
)

// CD Read Sizes
const (
	SAMPLE_SIZE             = 4
	CHANNEL_SIZE            = 12
	SECTOR_DATA_SIZE        = 2352
	SECTOR_C2_SIZE          = 294
	SECTOR_SUB_SIZE         = 96
	SECTOR_PAD_SIZE         = 2
	SECTOR_SYNC_SIZE        = 12
	SECTOR_DATA_C2_SIZE     = SECTOR_DATA_SIZE + SECTOR_C2_SIZE
	SECTOR_DATA_SUB_SIZE    = SECTOR_DATA_SIZE + SECTOR_SUB_SIZE
	SECTOR_DATA_C2_SUB_SIZE = SECTOR_DATA_SIZE + SECTOR_SUB_SIZE + SECTOR_C2_SIZE
	SECTOR_DATA_SUB_C2_SIZE = SECTOR_DATA_SIZE + SECTOR_C2_SIZE + SECTOR_SUB_SIZE
)
