name: Go-Pullrequest

permissions:
  contents: read
  actions: read
  pull-requests: read

on:
  pull_request:

env:
  release_name: build_${{github.run_number}}
  branch: ${{github.ref_name}}

jobs:
  build:
    uses: ./.github/workflows/go.yml